### ISSUE TITLE
开启 mathjax 后报错如下，不过到时可以正常显示公式。

### ISSUE THREAD

**Issue by chnwentao** [Molunerfinn/hexo-theme-melody#12]
⇒  hexo s --debug
08:25:15.811 DEBUG Hexo version: 3.4.2
08:25:15.813 DEBUG Working directory: ~/Library/Mobile Documents/com~apple~CloudDocs/blog/
08:25:15.953 DEBUG Config loaded: ~/Library/Mobile Documents/com~apple~CloudDocs/blog/_config.yml
08:25:15.976 DEBUG Plugin loaded: hexo-generator-archive
08:25:15.982 DEBUG Plugin loaded: hexo-deployer-git
08:25:15.984 DEBUG Plugin loaded: hexo-algoliasearch
08:25:15.987 DEBUG Plugin loaded: hexo-generator-category
08:25:15.989 DEBUG Plugin loaded: hexo-generator-tag
08:25:15.991 DEBUG Plugin loaded: hexo-generator-index
08:25:16.001 DEBUG Plugin loaded: hexo-generator-search
08:25:16.341 DEBUG Plugin loaded: hexo-inject
08:25:16.349 DEBUG Plugin loaded: hexo-jupyter-notebook
08:25:16.404 INFO  [hexo-math] Using engine 'mathjax'
08:25:16.405 DEBUG Plugin loaded: hexo-math
08:25:16.411 DEBUG Plugin loaded: hexo-renderer-ejs
08:25:16.856 DEBUG Plugin loaded: hexo-renderer-jade
08:25:16.900 DEBUG Plugin loaded: hexo-renderer-stylus
08:25:16.903 DEBUG Plugin loaded: hexo-renderer-markdown-it
08:25:16.970 DEBUG Plugin loaded: hexo-wordcount
08:25:17.065 DEBUG Plugin loaded: hexo-server
08:25:17.069 DEBUG Script loaded: themes/melody/scripts/hexo-plugins.txt
08:25:17.069 DEBUG Script loaded: themes/melody/scripts/replace-config.js
08:25:17.070 DEBUG [hexo-inject] firing inject_ready
Unhandled rejection TypeError: Invalid attempt to destructure non-iterable instance
    at /Users/wente/Library/Mobile Documents/com~apple~CloudDocs/blog/node_modules/hexo-inject/lib/util.js:7:585
    at parse (/Users/wente/Library/Mobile Documents/com~apple~CloudDocs/blog/node_modules/hexo-inject/lib/util.js:32:34)
    at Array.map (<anonymous>)
    at callsite (/Users/wente/Library/Mobile Documents/com~apple~CloudDocs/blog/node_modules/hexo-inject/lib/util.js:52:4)
    at Inject.require (/Users/wente/Library/Mobile Documents/com~apple~CloudDocs/blog/node_modules/hexo-inject/lib/mixin/require.js:100:55)
    at Object.require (/Users/wente/Library/Mobile Documents/com~apple~CloudDocs/blog/node_modules/hexo-inject/lib/inject.js:65:21)
    at Inject._injectMathJax (/Users/wente/Library/Mobile Documents/com~apple~CloudDocs/blog/node_modules/hexo-math/lib/filter/inject.js:43:22)
    at Hexo.tryCatcher (/Users/wente/Library/Mobile Documents/com~apple~CloudDocs/blog/node_modules/bluebird/js/release/util.js:16:23)
    at Hexo.<anonymous> (/Users/wente/Library/Mobile Documents/com~apple~CloudDocs/blog/node_modules/bluebird/js/release/method.js:15:34)
    at /Users/wente/Library/Mobile Documents/com~apple~CloudDocs/blog/node_modules/hexo/lib/extend/filter.js:68:35
    at tryCatcher (/Users/wente/Library/Mobile Documents/com~apple~CloudDocs/blog/node_modules/bluebird/js/release/util.js:16:23)
    at Object.gotValue (/Users/wente/Library/Mobile Documents/com~apple~CloudDocs/blog/node_modules/bluebird/js/release/reduce.js:155:18)
    at Object.gotAccum (/Users/wente/Library/Mobile Documents/com~apple~CloudDocs/blog/node_modules/bluebird/js/release/reduce.js:144:25)
    at Object.tryCatcher (/Users/wente/Library/Mobile Documents/com~apple~CloudDocs/blog/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/wente/Library/Mobile Documents/com~apple~CloudDocs/blog/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/wente/Library/Mobile Documents/com~apple~CloudDocs/blog/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromiseCtx (/Users/wente/Library/Mobile Documents/com~apple~CloudDocs/blog/node_modules/bluebird/js/release/promise.js:606:10)
    at Async._drainQueue (/Users/wente/Library/Mobile Documents/com~apple~CloudDocs/blog/node_modules/bluebird/js/release/async.js:138:12)
    at Async._drainQueues (/Users/wente/Library/Mobile Documents/com~apple~CloudDocs/blog/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/wente/Library/Mobile Documents/com~apple~CloudDocs/blog/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)

08:25:17.080 DEBUG Loading database.

**Comment by Molunerfinn** [comment]
mathjax采用CDN形式引入，跟hexo本身关系不大，可以忽略。
