### ISSUE TITLE
hexo g 时css 报错，帮忙解决一下（git新手）

### ISSUE THREAD

**Issue by Julythinkpad** [Molunerfinn/hexo-theme-melody#139]
图片在下面，第一次上传，不知道能不能行，感谢作者
![image](https://user-images.githubusercontent.com/27802843/44618420-e46aa800-a8a7-11e8-81dc-3c3ad93d999d.png)

错误提示如下：
`
ERROR /data/www/sugsfree/themes/melody/layout/includes/layout.pug:31
    29|       each url in theme.stylesheets
    30|         link(rel='stylesheet', href=url_for(url) + '?version=' + version  ())
  > 31|     each item in theme.cdn.css
    32|       if item !== undefined
    33|         link(rel='stylesheet', href=item + '?version=' + version())
    34|     include ./head.pug

Cannot read property 'css' of undefined
TypeError: /data/www/sugsfree/themes/melody/layout/includes/layout.pug:31
    29|       each url in theme.stylesheets
    30|         link(rel='stylesheet', href=url_for(url) + '?version=' + version  ())
  > 31|     each item in theme.cdn.css
    32|       if item !== undefined
    33|         link(rel='stylesheet', href=item + '?version=' + version())
    34|     include ./head.pug

Cannot read property 'css' of undefined
    at eval (eval at wrap (/data/www/sugsfree/node_modules/pug-runtime/wrap.js:6  :10), <anonymous>:80:25)
    at eval (eval at wrap (/data/www/sugsfree/node_modules/pug-runtime/wrap.js:6  :10), <anonymous>:102:4)
    at template (eval at wrap (/data/www/sugsfree/node_modules/pug-runtime/wrap.  js:6:10), <anonymous>:1759:72)
    at Theme._View.View._compiled.locals [as _compiled] (/data/www/sugsfree/node  _modules/hexo/lib/theme/view.js:124:48)
    at Theme._View.View.View.render (/data/www/sugsfree/node_modules/hexo/lib/th  eme/view.js:29:15)
    at route.set (/data/www/sugsfree/node_modules/hexo/lib/hexo/index.js:386:29)
    at tryCatcher (/data/www/sugsfree/node_modules/bluebird/js/release/util.js:1  6:23)
    at /data/www/sugsfree/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/data/www/sugsfree/node_modules/hexo/lib/hexo/router.j  s:134:3)
    at RouteStream.Readable.read (_stream_readable.js:442:10)
    at resume_ (_stream_readable.js:822:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
ERROR Asset render failed: css/index.css
Error: /data/www/sugsfree/node_modules/stylus/lib/functions/index.styl:128:38
   124|
   125| // darken by the given amount
   126|
   127| darken(color, amount)
   128|   adjust(color, 'lightness', - amount)
---------------------------------------------^
   129|
   130| // lighten by the given amount
   131|

TypeError: expected rgba or hsla, but got ident:$highlight-background
    at "&:after" (/data/www/sugsfree/themes/melody/source/css/_highlight/highlig  ht.styl:68:23)
    at ".highlight" (/data/www/sugsfree/themes/melody/source/css/_highlight/high  light.styl:63:24)
    at ".article-container" (/data/www/sugsfree/themes/melody/source/css/_highli  ght/highlight.styl:42:27)

    at Object.exports.assertColor (/data/www/sugsfree/node_modules/stylus/lib/ut  ils.js:255:13)
    at Evaluator.adjust (/data/www/sugsfree/node_modules/stylus/lib/functions/ad  just.js:14:9)
    at Evaluator.invokeBuiltin (/data/www/sugsfree/node_modules/stylus/lib/visit  or/evaluator.js:1051:30)
    at Evaluator.visitCall (/data/www/sugsfree/node_modules/stylus/lib/visitor/e  valuator.js:516:16)
    at Evaluator.Visitor.visit (/data/www/sugsfree/node_modules/stylus/lib/visit  or/index.js:28:40)
    at Evaluator.visit (/data/www/sugsfree/node_modules/stylus/lib/visitor/evalu  ator.js:160:18)
    at Evaluator.visitExpression (/data/www/sugsfree/node_modules/stylus/lib/vis  itor/evaluator.js:644:26)
    at Evaluator.Visitor.visit (/data/www/sugsfree/node_modules/stylus/lib/visit  or/index.js:28:40)
    at Evaluator.visit (/data/www/sugsfree/node_modules/stylus/lib/visitor/evalu  ator.js:160:18)
    at Evaluator.eval (/data/www/sugsfree/node_modules/stylus/lib/visitor/evalua  tor.js:1235:23)
    at Evaluator.invoke (/data/www/sugsfree/node_modules/stylus/lib/visitor/eval  uator.js:1080:16)
    at Evaluator.invokeFunction (/data/www/sugsfree/node_modules/stylus/lib/visi  tor/evaluator.js:1012:15)
    at Evaluator.visitCall (/data/www/sugsfree/node_modules/stylus/lib/visitor/e  valuator.js:522:16)
    at Evaluator.Visitor.visit (/data/www/sugsfree/node_modules/stylus/lib/visit  or/index.js:28:40)
    at Evaluator.visit (/data/www/sugsfree/node_modules/stylus/lib/visitor/evalu  ator.js:160:18)
    at Evaluator.visitExpression (/data/www/sugsfree/node_modules/stylus/lib/vis  itor/evaluator.js:644:26)
    at Evaluator.Visitor.visit (/data/www/sugsfree/node_modules/stylus/lib/visit  or/index.js:28:40)
    at Evaluator.visit (/data/www/sugsfree/node_modules/stylus/lib/visitor/evalu  ator.js:160:18)
    at Evaluator.visitProperty (/data/www/sugsfree/node_modules/stylus/lib/visit  or/evaluator.js:676:31)
    at Evaluator.Visitor.visit (/data/www/sugsfree/node_modules/stylus/lib/visit  or/index.js:28:40)
    at Evaluator.visit (/data/www/sugsfree/node_modules/stylus/lib/visitor/evalu  ator.js:160:18)
    at Evaluator.visitBlock (/data/www/sugsfree/node_modules/stylus/lib/visitor/  evaluator.js:720:39)
`
配置文件：
`
# Hexo Configuration
## Source: https://github.com/hexojs/hexo/

# Site
title: Gs0nlyu_Star2
subtitle:
description:
keywords:
author: John Doe
language: zh-Hans
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://www.sugsfree.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: false
  auto_detect: false
  tab_replace:

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Themes: https://hexo.io/themes/
theme: melody

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type:
 # repo: ssh://git@www.sugsfree.com:28823/var/repo/blog.git
 # branch: master
  # message: Hexo update
`

**Comment by Molunerfinn** [comment]
不管是不是新手，你都不应该无视issue发帖规范，你看过文档了吗，看过前面的人发过的issue了吗？请问你主题的配置文件在哪里？你给的不过是hexo站点的配置文件。
不按发帖规范的issue将直接被关闭。


 :octocat: [From gitme iOS](http://flutterchina.club/app/gm.html)

**Comment by upupming** [comment]
@Julythinkpad 看错误信息大概是没有配置好 `cdn` 这个选项。提问之前请一定仔细阅读文档，文档能解决大部分问题。如果您还需要帮助的话，一定按照规范来提出 issue。

另外粘贴代码的时候请使用 \`\`，或者 `<pre>`、`<details>` 标签，随时查阅 [Markdown Cheatsheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)。长代码还可以直接引用 GitHub 上的文件，或者像 https://paste.ubuntu.com 的粘贴代码服务。
