### ISSUE TITLE
hexo s 报错

### ISSUE THREAD

**Issue by ChungZH** [Molunerfinn/hexo-theme-melody#173]
## I want to create a new issue  

- [x] Yes, I have read [FAQ](https://github.com/Molunerfinn/hexo-theme-melody/blob/dev/FAQ.md).
- [x] Yes, I have read [Hexo Docs page](https://hexo.io/docs/), especially [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I have read [Hexo-theme-melody Documentation](https://molunerfinn.com/hexo-theme-melody-doc/).
- [x] And yes, I already searched for current [issues](https://github.com/Molunerfinn/hexo-theme-melody/issues?utf8=%E2%9C%93&q=is%3Aissue) and this did not help me.

## Melody Information

**Melody Version:**
最新版

**Platform:**
Windows

**Browser:**
FireFox
## Expected behavior 
`hexo s` 正常运行。
## Actual behavior 
报错。

![](https://chungzhblog-photo.oss-cn-shenzhen.aliyuncs.com/githubissuepic/%E6%89%B9%E6%B3%A8%202019-01-22%20154358.png)
报错信息：
```bash
Unhandled rejection TypeError: E:\MyStudio\xx\ChungZH_blog\Blog\themes\melody\layout\includes\config.pug:1
  > 1| -
    2|   var algolia = 'undefined';
    3|   var env = process.env;
    4|   if (theme.algolia_search.enable) {

Cannot read property 'path' of undefined
    at eval (eval at wrap (E:\MyStudio\xx\ChungZH_blog\Blog\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:345:25)
    at template (eval at wrap (E:\MyStudio\xx\ChungZH_blog\Blog\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:1801:72)
    at Theme._View.View._compiled.locals [as _compiled] (E:\MyStudio\xx\ChungZH_blog\Blog\node_modules\hexo\lib\theme\view.js:125:48)
    at Theme._View.View.View.render (E:\MyStudio\xx\ChungZH_blog\Blog\node_modules\hexo\lib\theme\view.js:30:15)
    at route.set (E:\MyStudio\xx\ChungZH_blog\Blog\node_modules\hexo\lib\hexo\index.js:394:29)
    at tryCatcher (E:\MyStudio\xx\ChungZH_blog\Blog\node_modules\bluebird\js\release\util.js:16:23)
    at E:\MyStudio\xx\ChungZH_blog\Blog\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (E:\MyStudio\xx\ChungZH_blog\Blog\node_modules\hexo\lib\hexo\router.js:134:3)
    at RouteStream.Readable.read (_stream_readable.js:442:10)
    at resume_ (_stream_readable.js:822:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

Unhandled rejection TypeError: E:\MyStudio\xx\ChungZH_blog\Blog\themes\melody\layout\includes\config.pug:1
  > 1| -
    2|   var algolia = 'undefined';
    3|   var env = process.env;
    4|   if (theme.algolia_search.enable) {

Cannot read property 'path' of undefined
    at eval (eval at wrap (E:\MyStudio\xx\ChungZH_blog\Blog\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:345:25)
    at template (eval at wrap (E:\MyStudio\xx\ChungZH_blog\Blog\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:1801:72)
    at Theme._View.View._compiled.locals [as _compiled] (E:\MyStudio\xx\ChungZH_blog\Blog\node_modules\hexo\lib\theme\view.js:125:48)
    at Theme._View.View.View.render (E:\MyStudio\xx\ChungZH_blog\Blog\node_modules\hexo\lib\theme\view.js:30:15)
    at route.set (E:\MyStudio\xx\ChungZH_blog\Blog\node_modules\hexo\lib\hexo\index.js:394:29)
    at tryCatcher (E:\MyStudio\xx\ChungZH_blog\Blog\node_modules\bluebird\js\release\util.js:16:23)
    at E:\MyStudio\xx\ChungZH_blog\Blog\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (E:\MyStudio\xx\ChungZH_blog\Blog\node_modules\hexo\lib\hexo\router.js:134:3)
    at RouteStream.Readable.read (_stream_readable.js:442:10)
    at resume_ (_stream_readable.js:822:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

应该是没有重复安装两种 jade 渲染器。

附 `package.json`：
```json
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.8.0"
  },
  "dependencies": {
    "hexo": "^3.7.0",
    "hexo-generator-archive": "^0.1.5",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-index": "^0.2.1",
    "hexo-generator-tag": "^0.2.0",
    "hexo-renderer-ejs": "^0.3.1",
    "hexo-renderer-jade": "^0.4.1",
    "hexo-renderer-marked": "^0.3.2",
    "hexo-renderer-stylus": "^0.3.3",
    "hexo-server": "^0.3.1"
  }
}

```

## Feature Request

---

**Comment by Molunerfinn** [comment]
把你的melody的配置文件发上来看看

**Comment by ChungZH** [comment]
好了谢谢，太心急了，连插件都没装好就直接把配置文件复制到新的 Hexo 里了 :joy:
