### ISSUE TITLE
首页正常显示，文章页空白无法显示

### ISSUE THREAD

**Issue by ResidualNight** [Molunerfinn/hexo-theme-melody#177]
## I want to create a new issue  

- [] Yes, I have read [FAQ](https://github.com/Molunerfinn/hexo-theme-melody/blob/dev/FAQ.md).
- [] Yes, I have read [Hexo Docs page](https://hexo.io/docs/), especially [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [] Yes, I have read [Hexo-theme-melody Documentation](https://molunerfinn.com/hexo-theme-melody-doc/).
- [] And yes, I already searched for current [issues](https://github.com/Molunerfinn/hexo-theme-melody/issues?utf8=%E2%9C%93&q=is%3Aissue) and this did not help me.

## Melody Information

**Melody Version:** the latest version on 2019.2.15

**Platform:** macOS

**Browser:** Chrome

## Expected behavior 

正常显示博客

## Actual behavior 
hexo g时出错，但最终可以成功编译上传

只是一个学过一点cpp的初中苣蒻，又找不到解决方法，只好请教：

```
ERROR /Users/apple/blog/themes/melody/layout/includes/share/index.pug:1
  > 1| if theme.addThis.enable
    2|   include ./add-this.pug
    3| else if theme.sharejs && theme.sharejs.enable
    4|   include ./share-js.pug

Cannot read property 'enable' of undefined
TypeError: /Users/apple/blog/themes/melody/layout/includes/share/index.pug:1
  > 1| if theme.addThis.enable
    2|   include ./add-this.pug
    3| else if theme.sharejs && theme.sharejs.enable
    4|   include ./share-js.pug

Cannot read property 'enable' of undefined
    at eval (eval at wrap (/Users/apple/blog/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:1144:19)
    at template (eval at wrap (/Users/apple/blog/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:1978:72)
    at Theme._View.View._compiled.locals [as _compiled] (/Users/apple/blog/node_modules/hexo/lib/theme/view.js:125:48)
    at Theme._View.View.View.render (/Users/apple/blog/node_modules/hexo/lib/theme/view.js:30:15)
    at route.set (/Users/apple/blog/node_modules/hexo/lib/hexo/index.js:394:29)
    at tryCatcher (/Users/apple/blog/node_modules/bluebird/js/release/util.js:16:23)
    at /Users/apple/blog/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/Users/apple/blog/node_modules/hexo/lib/hexo/router.js:134:3)
    at RouteStream.Readable.read (_stream_readable.js:452:10)
    at resume_ (_stream_readable.js:899:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
ERROR /Users/apple/blog/themes/melody/layout/includes/share/index.pug:1
  > 1| if theme.addThis.enable
    2|   include ./add-this.pug
    3| else if theme.sharejs && theme.sharejs.enable
    4|   include ./share-js.pug

Cannot read property 'enable' of undefined
TypeError: /Users/apple/blog/themes/melody/layout/includes/share/index.pug:1
  > 1| if theme.addThis.enable
    2|   include ./add-this.pug
    3| else if theme.sharejs && theme.sharejs.enable
    4|   include ./share-js.pug

Cannot read property 'enable' of undefined
    at eval (eval at wrap (/Users/apple/blog/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:1144:19)
    at template (eval at wrap (/Users/apple/blog/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:1978:72)
    at Theme._View.View._compiled.locals [as _compiled] (/Users/apple/blog/node_modules/hexo/lib/theme/view.js:125:48)
    at Theme._View.View.View.render (/Users/apple/blog/node_modules/hexo/lib/theme/view.js:30:15)
    at route.set (/Users/apple/blog/node_modules/hexo/lib/hexo/index.js:394:29)
    at tryCatcher (/Users/apple/blog/node_modules/bluebird/js/release/util.js:16:23)
    at /Users/apple/blog/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/Users/apple/blog/node_modules/hexo/lib/hexo/router.js:134:3)
    at RouteStream.Readable.read (_stream_readable.js:452:10)
    at resume_ (_stream_readable.js:899:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
ERROR /Users/apple/blog/themes/melody/layout/includes/share/index.pug:1
  > 1| if theme.addThis.enable
    2|   include ./add-this.pug
    3| else if theme.sharejs && theme.sharejs.enable
    4|   include ./share-js.pug

Cannot read property 'enable' of undefined
TypeError: /Users/apple/blog/themes/melody/layout/includes/share/index.pug:1
  > 1| if theme.addThis.enable
    2|   include ./add-this.pug
    3| else if theme.sharejs && theme.sharejs.enable
    4|   include ./share-js.pug

Cannot read property 'enable' of undefined
    at eval (eval at wrap (/Users/apple/blog/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:1144:19)
    at template (eval at wrap (/Users/apple/blog/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:1978:72)
    at Theme._View.View._compiled.locals [as _compiled] (/Users/apple/blog/node_modules/hexo/lib/theme/view.js:125:48)
    at Theme._View.View.View.render (/Users/apple/blog/node_modules/hexo/lib/theme/view.js:30:15)
    at route.set (/Users/apple/blog/node_modules/hexo/lib/hexo/index.js:394:29)
    at tryCatcher (/Users/apple/blog/node_modules/bluebird/js/release/util.js:16:23)
    at /Users/apple/blog/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/Users/apple/blog/node_modules/hexo/lib/hexo/router.js:134:3)
    at RouteStream.Readable.read (_stream_readable.js:452:10)
    at resume_ (_stream_readable.js:899:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
ERROR /Users/apple/blog/themes/melody/layout/includes/share/index.pug:1
  > 1| if theme.addThis.enable
    2|   include ./add-this.pug
    3| else if theme.sharejs && theme.sharejs.enable
    4|   include ./share-js.pug

Cannot read property 'enable' of undefined
TypeError: /Users/apple/blog/themes/melody/layout/includes/share/index.pug:1
  > 1| if theme.addThis.enable
    2|   include ./add-this.pug
    3| else if theme.sharejs && theme.sharejs.enable
    4|   include ./share-js.pug

Cannot read property 'enable' of undefined
    at eval (eval at wrap (/Users/apple/blog/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:1144:19)
    at template (eval at wrap (/Users/apple/blog/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:1978:72)
    at Theme._View.View._compiled.locals [as _compiled] (/Users/apple/blog/node_modules/hexo/lib/theme/view.js:125:48)
    at Theme._View.View.View.render (/Users/apple/blog/node_modules/hexo/lib/theme/view.js:30:15)
    at route.set (/Users/apple/blog/node_modules/hexo/lib/hexo/index.js:394:29)
    at tryCatcher (/Users/apple/blog/node_modules/bluebird/js/release/util.js:16:23)
    at /Users/apple/blog/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/Users/apple/blog/node_modules/hexo/lib/hexo/router.js:134:3)
    at RouteStream.Readable.read (_stream_readable.js:452:10)
    at resume_ (_stream_readable.js:899:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

主页、tag页面显示正常，但是博文页面显示不正常，打开源代码竟是白的

提交前看了看其他提问，我的短文章也显示不了啊！

http://t1.aixinxi.net/o_1d3ok1rnf15bp1q9u5a28hk1gl6a.png-w.jpg

http://t1.aixinxi.net/o_1d3ok4b7g71d15u5u918181oa9a.png-w.jpg

## Feature Request

可以考虑一下置顶功能吗？谢谢大佬！

---

**Comment by Molunerfinn** [comment]
![image](https://user-images.githubusercontent.com/12621342/52859344-6a84ee80-3167-11e9-8660-f44fe0c5cede.png)
你主题配置项里的`addThis`配置有问题，`enable`值不见了。
![image](https://user-images.githubusercontent.com/12621342/52859397-8be5da80-3167-11e9-953a-f26d1168e957.png)
如果不想开启`addThis`也不能把这个配置项删掉，把它的`enable`置为`false`。不要轻易删除配置项，或者注释配置项，不想开启的功能通常只需要把`enable`置成`false`即可。
置顶功能在`dev`分支已经实现，不过需要额外的插件支持，目前我还没有时间写出文档。

**Comment by ResidualNight** [comment]
好的，感谢

**Comment by JunzhouLiu** [comment]
开学我有空了可以帮你补一下文档。
________________________________

**Comment by Molunerfinn** [comment]
@JunzhouLiu 哈哈暂时还不用，因为`dev`分支的东西还没做完1.6全部的功能。等全部功能做完了我会开始整理更新日志。
如果到时候感兴趣，可以等我更新日志出来后，来写写中文文档，我会把英文版本的文档先给上~

**Comment by JunzhouLiu** [comment]
@Molunerfinn 好的哈

**Comment by wnxy** [comment]
> ![image](https://user-images.githubusercontent.com/12621342/52859344-6a84ee80-3167-11e9-8660-f44fe0c5cede.png) 你主题配置项里的`addThis`配置有问题，`enable`值不见了。 ![image](https://user-images.githubusercontent.com/12621342/52859397-8be5da80-3167-11e9-953a-f26d1168e957.png) 如果不想开启`addThis`也不能把这个配置项删掉，把它的`enable`置为`false`。不要轻易删除配置项，或者注释配置项，不想开启的功能通常只需要把`enable`置成`false`即可。 置顶功能在`dev`分支已经实现，不过需要额外的插件支持，目前我还没有时间写出文档。 如果没有其他的问题，你改完发现可以了就可以把这个issue关闭了，如果仍然有问题就把报错信息继续贴上来

你好，我按照https://molunerfinn.com/hexo-theme-melody-doc/zh-Hans/ 文档的步骤成功安装hexo melody主题博客，
其中hexo g执行过程如下：
```
PS F:\blog> hexo g
INFO  Validating config
INFO  Start processing
INFO  Files loaded in 2.23 s
INFO  Generated: atom.xml
INFO  Generated: archives/index.html
INFO  Generated: sitemap.xml
INFO  Generated: sitemap.txt
INFO  Generated: archives/2022/index.html
INFO  Generated: archives/2022/05/index.html
INFO  Generated: img/avatar.png
INFO  Generated: melody-favicon.ico
INFO  Generated: index.html
INFO  Generated: js/hexo-theme-melody.js
INFO  Generated: img/algolia.svg
INFO  Generated: css/var.css
INFO  Generated: js/search/algolia.js
INFO  Generated: js/third-party/anime.min.js
INFO  Generated: js/third-party/reveal/head.min.js
INFO  Generated: css/404.css
INFO  Generated: js/fancybox.js
INFO  Generated: js/copy.js
INFO  Generated: js/fireworks.js
INFO  Generated: js/head.js
INFO  Generated: js/katex.js
INFO  Generated: js/search/local-search.js
INFO  Generated: js/scroll.js
INFO  Generated: js/third-party/canvas-ribbon.js
INFO  Generated: js/third-party/velocity.ui.min.js
INFO  Generated: js/transition.js
INFO  Generated: js/utils.js
INFO  Generated: js/sidebar.js
INFO  Generated: 2022/05/29/hello-world/index.html
INFO  Generated: css/index.css
INFO  Generated: js/third-party/velocity.min.js
INFO  Generated: js/third-party/jquery.fancybox.min.js
INFO  Generated: js/third-party/jquery.min.js
INFO  33 files generated in 720 ms
```
但是hexo s 后，查看结果，发现博客没有文章（博客站点下面有一篇自动创建的名为 hello world的文章）
![image](https://user-images.githubusercontent.com/38371856/170857668-1b51c08f-373a-430c-9db5-820f86610266.png)
有什么解决方法吗？
