### ISSUE TITLE
参照官方配置，进行到复制_config.yml到_data目录的melody.yml后编译出错

### ISSUE THREAD

**Issue by michaeljfei** [Molunerfinn/hexo-theme-melody#25]
Unhandled rejection TypeError: /Users/michael/Desktop/blog/themes/melody/layout/includes/layout.pug:31
    29|       each url in theme.stylesheets
    30|         link(rel='stylesheet', href=url)
  > 31|     each item in theme.cdn.css
    32|       if item !== undefined
    33|         link(rel='stylesheet', href=item + '?version=' + theme.version)
    34|     include ./head.pug

Cannot read property 'css' of undefined
    at eval (eval at wrap (/Users/michael/Desktop/blog/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:80:25)
    at eval (eval at wrap (/Users/michael/Desktop/blog/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:102:4)
    at template (eval at wrap (/Users/michael/Desktop/blog/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:1037:72)
    at Theme._View.View._compiled (/Users/michael/Desktop/blog/node_modules/hexo/lib/theme/view.js:127:30)
    at Theme._View.View.View.render (/Users/michael/Desktop/blog/node_modules/hexo/lib/theme/view.js:29:15)
    at /Users/michael/Desktop/blog/node_modules/hexo/lib/hexo/index.js:390:25
    at tryCatcher (/Users/michael/Desktop/blog/node_modules/bluebird/js/release/util.js:16:23)
    at /Users/michael/Desktop/blog/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/Users/michael/Desktop/blog/node_modules/hexo/lib/hexo/router.js:134:3)
    at RouteStream.Readable.read (_stream_readable.js:442:10)
    at resume_ (_stream_readable.js:822:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

Unhandled rejection TypeError: /Users/michael/Desktop/blog/themes/melody/layout/includes/layout.pug:31
    29|       each url in theme.stylesheets
    30|         link(rel='stylesheet', href=url)
  > 31|     each item in theme.cdn.css
    32|       if item !== undefined
    33|         link(rel='stylesheet', href=item + '?version=' + theme.version)
    34|     include ./head.pug

Cannot read property 'css' of undefined
    at eval (eval at wrap (/Users/michael/Desktop/blog/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:80:25)
    at eval (eval at wrap (/Users/michael/Desktop/blog/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:102:4)
    at template (eval at wrap (/Users/michael/Desktop/blog/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:1037:72)
    at Theme._View.View._compiled (/Users/michael/Desktop/blog/node_modules/hexo/lib/theme/view.js:127:30)
    at Theme._View.View.View.render (/Users/michael/Desktop/blog/node_modules/hexo/lib/theme/view.js:29:15)
    at /Users/michael/Desktop/blog/node_modules/hexo/lib/hexo/index.js:390:25
    at tryCatcher (/Users/michael/Desktop/blog/node_modules/bluebird/js/release/util.js:16:23)
    at /Users/michael/Desktop/blog/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/Users/michael/Desktop/blog/node_modules/hexo/lib/hexo/router.js:134:3)
    at RouteStream.Readable.read (_stream_readable.js:442:10)
    at resume_ (_stream_readable.js:822:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by Molunerfinn** [comment]
请问你复制的`_config.yml`是hexo配置的`_config.yml`还是melody主题自带的`_config.yml`？需要复制的是melody主题自带的`_config.yml`。请给出你的`melody.yml`的内容。按报错信息来看是缺少了cdn属性的css属性。

**Comment by michaeljfei** [comment]
不好意思，的确是复制的官方hexo生成的_config.yml导致出错的，没有看清楚
