### ISSUE TITLE
在执行hexo generate出错

### ISSUE THREAD

**Issue by pengbeilin** [Molunerfinn/hexo-theme-melody#254]
在执行hexo generate出错

`
D:\blog\node_modules\.bin>hexo generate
INFO  Start processing
INFO  Files loaded in 2.61 s
ERROR D:\blog\themes\melody\layout\includes\layout.pug:31
    29|       each url in theme.stylesheets
    30|         link(rel='stylesheet', href=url_for(url) + '?version=' + version())
  > 31|     each item in theme.cdn.css
    32|       if item !== undefined
    33|         link(rel='stylesheet', href=item + '?version=' + version())
    34|     include ./head.pug

Cannot read property 'css' of undefined
TypeError: D:\blog\themes\melody\layout\includes\layout.pug:31
    29|       each url in theme.stylesheets
    30|         link(rel='stylesheet', href=url_for(url) + '?version=' + version())
  > 31|     each item in theme.cdn.css
    32|       if item !== undefined
    33|         link(rel='stylesheet', href=item + '?version=' + version())
    34|     include ./head.pug

Cannot read property 'css' of undefined
    at eval (eval at wrap (D:\blog\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:80:25)
    at eval (eval at wrap (D:\blog\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:102:4)
    at template (eval at wrap (D:\blog\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:2130:72)
    at Theme._View.View._compiled.locals [as _compiled] (D:\blog\node_modules\hexo\lib\theme\view.js:123:48)
    at Theme._View.View.View.render (D:\blog\node_modules\hexo\lib\theme\view.js:29:15)
    at D:\blog\node_modules\hexo\lib\hexo\index.js:365:21
    at tryCatcher (D:\blog\node_modules\bluebird\js\release\util.js:16:23)
    at D:\blog\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (D:\blog\node_modules\hexo\lib\hexo\router.js:123:3)
    at RouteStream.Readable.read (_stream_readable.js:453:10)
    at resume_ (_stream_readable.js:929:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
ERROR D:\blog\themes\melody\layout\includes\layout.pug:31
    29|       each url in theme.stylesheets
    30|         link(rel='stylesheet', href=url_for(url) + '?version=' + version())
  > 31|     each item in theme.cdn.css
    32|       if item !== undefined
    33|         link(rel='stylesheet', href=item + '?version=' + version())
    34|     include ./head.pug

Cannot read property 'css' of undefined
TypeError: D:\blog\themes\melody\layout\includes\layout.pug:31
    29|       each url in theme.stylesheets
    30|         link(rel='stylesheet', href=url_for(url) + '?version=' + version())
  > 31|     each item in theme.cdn.css
    32|       if item !== undefined
    33|         link(rel='stylesheet', href=item + '?version=' + version())
    34|     include ./head.pug

Cannot read property 'css' of undefined
    at eval (eval at wrap (D:\blog\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:80:25)
    at eval (eval at wrap (D:\blog\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:102:4)
    at template (eval at wrap (D:\blog\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:1271:72)
    at Theme._View.View._compiled.locals [as _compiled] (D:\blog\node_modules\hexo\lib\theme\view.js:123:48)
    at Theme._View.View.View.render (D:\blog\node_modules\hexo\lib\theme\view.js:29:15)
    at D:\blog\node_modules\hexo\lib\hexo\index.js:365:21
    at tryCatcher (D:\blog\node_modules\bluebird\js\release\util.js:16:23)
    at D:\blog\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (D:\blog\node_modules\hexo\lib\hexo\router.js:123:3)
    at RouteStream.Readable.read (_stream_readable.js:453:10)
    at resume_ (_stream_readable.js:929:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
ERROR D:\blog\themes\melody\layout\includes\layout.pug:31
    29|       each url in theme.stylesheets
    30|         link(rel='stylesheet', href=url_for(url) + '?version=' + version())
  > 31|     each item in theme.cdn.css
    32|       if item !== undefined
    33|         link(rel='stylesheet', href=item + '?version=' + version())
    34|     include ./head.pug

Cannot read property 'css' of undefined
TypeError: D:\blog\themes\melody\layout\includes\layout.pug:31
    29|       each url in theme.stylesheets
    30|         link(rel='stylesheet', href=url_for(url) + '?version=' + version())
  > 31|     each item in theme.cdn.css
    32|       if item !== undefined
    33|         link(rel='stylesheet', href=item + '?version=' + version())
    34|     include ./head.pug

Cannot read property 'css' of undefined
    at eval (eval at wrap (D:\blog\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:80:25)
    at eval (eval at wrap (D:\blog\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:102:4)
    at template (eval at wrap (D:\blog\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:1271:72)
    at Theme._View.View._compiled.locals [as _compiled] (D:\blog\node_modules\hexo\lib\theme\view.js:123:48)
    at Theme._View.View.View.render (D:\blog\node_modules\hexo\lib\theme\view.js:29:15)
    at D:\blog\node_modules\hexo\lib\hexo\index.js:365:21
    at tryCatcher (D:\blog\node_modules\bluebird\js\release\util.js:16:23)
    at D:\blog\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (D:\blog\node_modules\hexo\lib\hexo\router.js:123:3)
    at RouteStream.Readable.read (_stream_readable.js:453:10)
    at resume_ (_stream_readable.js:929:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
ERROR D:\blog\themes\melody\layout\includes\layout.pug:31
    29|       each url in theme.stylesheets
    30|         link(rel='stylesheet', href=url_for(url) + '?version=' + version())
  > 31|     each item in theme.cdn.css
    32|       if item !== undefined
    33|         link(rel='stylesheet', href=item + '?version=' + version())
    34|     include ./head.pug

Cannot read property 'css' of undefined
TypeError: D:\blog\themes\melody\layout\includes\layout.pug:31
    29|       each url in theme.stylesheets
    30|         link(rel='stylesheet', href=url_for(url) + '?version=' + version())
  > 31|     each item in theme.cdn.css
    32|       if item !== undefined
    33|         link(rel='stylesheet', href=item + '?version=' + version())
    34|     include ./head.pug

Cannot read property 'css' of undefined
    at eval (eval at wrap (D:\blog\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:80:25)
    at eval (eval at wrap (D:\blog\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:102:4)
    at template (eval at wrap (D:\blog\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:1271:72)
    at Theme._View.View._compiled.locals [as _compiled] (D:\blog\node_modules\hexo\lib\theme\view.js:123:48)
    at Theme._View.View.View.render (D:\blog\node_modules\hexo\lib\theme\view.js:29:15)
    at D:\blog\node_modules\hexo\lib\hexo\index.js:365:21
    at tryCatcher (D:\blog\node_modules\bluebird\js\release\util.js:16:23)
    at D:\blog\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (D:\blog\node_modules\hexo\lib\hexo\router.js:123:3)
    at RouteStream.Readable.read (_stream_readable.js:453:10)
    at resume_ (_stream_readable.js:929:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
ERROR D:\blog\themes\melody\layout\includes\layout.pug:31
    29|       each url in theme.stylesheets
    30|         link(rel='stylesheet', href=url_for(url) + '?version=' + version())
  > 31|     each item in theme.cdn.css
    32|       if item !== undefined
    33|         link(rel='stylesheet', href=item + '?version=' + version())
    34|     include ./head.pug

Cannot read property 'css' of undefined
TypeError: D:\blog\themes\melody\layout\includes\layout.pug:31
    29|       each url in theme.stylesheets
    30|         link(rel='stylesheet', href=url_for(url) + '?version=' + version())
  > 31|     each item in theme.cdn.css
    32|       if item !== undefined
    33|         link(rel='stylesheet', href=item + '?version=' + version())
    34|     include ./head.pug

Cannot read property 'css' of undefined
    at eval (eval at wrap (D:\blog\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:80:25)
    at eval (eval at wrap (D:\blog\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:102:4)
    at template (eval at wrap (D:\blog\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:1825:72)
    at Theme._View.View._compiled.locals [as _compiled] (D:\blog\node_modules\hexo\lib\theme\view.js:123:48)
    at Theme._View.View.View.render (D:\blog\node_modules\hexo\lib\theme\view.js:29:15)
    at D:\blog\node_modules\hexo\lib\hexo\index.js:365:21
    at tryCatcher (D:\blog\node_modules\bluebird\js\release\util.js:16:23)
    at D:\blog\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (D:\blog\node_modules\hexo\lib\hexo\router.js:123:3)
    at RouteStream.Readable.read (_stream_readable.js:453:10)
    at resume_ (_stream_readable.js:929:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
ERROR Asset render failed: css/index.css
Error: D:/blog/node_modules/stylus/lib/functions/index.styl:128:3
   124|
   125| // darken by the given amount
   126|
   127| darken(color, amount)
   128|   adjust(color, 'lightness', - amount)
----------^
   129|
   130| // lighten by the given amount
   131|

TypeError: expected rgba or hsla, but got ident:$highlight-background
    at "&:after" (D:/blog/themes/melody/source/css/_highlight/highlight.styl:70:5)
    at ".highlight" (D:/blog/themes/melody/source/css/_highlight/highlight.styl:65:3)
    at ".article-container" (D:/blog/themes/melody/source/css/_highlight/highlight.styl:44:1)

    at Object.exports.assertColor (D:\blog\node_modules\stylus\lib\utils.js:255:13)
    at Evaluator.adjust (D:\blog\node_modules\stylus\lib\functions\adjust.js:14:9)
    at Evaluator.invokeBuiltin (D:\blog\node_modules\stylus\lib\visitor\evaluator.js:1054:30)
    at Evaluator.visitCall (D:\blog\node_modules\stylus\lib\visitor\evaluator.js:516:16)
    at Evaluator.Visitor.visit (D:\blog\node_modules\stylus\lib\visitor\index.js:28:40)
    at Evaluator.visit (D:\blog\node_modules\stylus\lib\visitor\evaluator.js:160:18)
    at Evaluator.visitExpression (D:\blog\node_modules\stylus\lib\visitor\evaluator.js:644:26)
    at Evaluator.Visitor.visit (D:\blog\node_modules\stylus\lib\visitor\index.js:28:40)
    at Evaluator.visit (D:\blog\node_modules\stylus\lib\visitor\evaluator.js:160:18)
    at Evaluator.eval (D:\blog\node_modules\stylus\lib\visitor\evaluator.js:1238:23)
    at Evaluator.invoke (D:\blog\node_modules\stylus\lib\visitor\evaluator.js:1083:16)
    at Evaluator.invokeFunction (D:\blog\node_modules\stylus\lib\visitor\evaluator.js:1012:15)
    at Evaluator.visitCall (D:\blog\node_modules\stylus\lib\visitor\evaluator.js:522:16)
    at Evaluator.Visitor.visit (D:\blog\node_modules\stylus\lib\visitor\index.js:28:40)
    at Evaluator.visit (D:\blog\node_modules\stylus\lib\visitor\evaluator.js:160:18)
    at Evaluator.visitExpression (D:\blog\node_modules\stylus\lib\visitor\evaluator.js:644:26)
`

**Comment by Molunerfinn** [comment]
配置文件问题，请仔细阅读文档，以及以前的人提过的issue:)
