### ISSUE TITLE
文章详情页无法渲染

### ISSUE THREAD

**Issue by royalbluewa3** [Molunerfinn/hexo-theme-melody#41]
更新了一下版本1.4.3后，出现详情页无法渲染的情况，首页正常。

ERROR D:\blog\themes\melody\layout\post.pug:23
>    21|               if (index < page.categories.data.length - 1)
    22|                  i.fa.fa-angle-right(aria-hidden="true")
   23|           if (theme.disqus.enable && theme.disqus.count)
    24|             if (theme.post_meta.date_type || theme.post_meta.categories && page.categories.data.length > 0)
    25|               span.post-meta__separator |
    26|             i.fa.fa-comment-o.post-meta__icon(aria-hidden="true")

Cannot read property 'enable' of undefined
TypeError: D:\blog\themes\melody\layout\post.pug:23
 >    21|               if (index < page.categories.data.length - 1)
    22|                  i.fa.fa-angle-right(aria-hidden="true")
  23|           if (theme.disqus.enable && theme.disqus.count)
    24|             if (theme.post_meta.date_type || theme.post_meta.categories && page.categories.data.length > 0)
    25|               span.post-meta__separator |
    26|             i.fa.fa-comment-o.post-meta__icon(aria-hidden="true")

Cannot read property 'enable' of undefined
 >   at eval (eval at wrap (D:\blog\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:745:19)
    at template (eval at wrap (D:\blog\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:1807:72)
    at Theme._View.View._compiled.locals [as _compiled] (D:\blog\node_modules\hexo\lib\theme\view.js:124:48)

>    at Theme._View.View.View.render (D:\blog\node_modules\hexo\lib\theme\view.js:29:15)
    at route.set (D:\blog\node_modules\hexo\lib\hexo\index.js:386:29)
    at tryCatcher (D:\blog\node_modules\bluebird\js\release\util.js:16:23)
    at D:\blog\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (D:\blog\node_modules\hexo\lib\hexo\router.js:134:3)
    at RouteStream.Readable.read (_stream_readable.js:442:10)
    at resume_ (_stream_readable.js:822:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by Molunerfinn** [comment]
应该是你配置文件里的`disqus`一项被你注释了或者删掉了。
注意，`disqus`一项是melody最早支持的评论系统。所以不管用不用disqus，都必须有disqus的enable字段。
如果不想启用它就是：
```yaml
disqus:
  enable: false
``
否则就会报如上的错误。
