### ISSUE TITLE
安装报错

### ISSUE THREAD

**Issue by coder163** [Molunerfinn/hexo-theme-melody#67]
主题对hexo的版本有要求吗？我使用的hexo3.2.0，配置完了提示错误：错误描述如下

ERROR Process failed: layout/includes/slide/script.pug
TypeError: Cannot read property 'compile' of undefined
    at Theme._View.View.View._precompile (E:\hexo\blog\node_modules\hexo\lib\theme\view.js:104:23)
    at Theme._View.View.View (E:\hexo\blog\node_modules\hexo\lib\theme\view.js:13:8)
    at new Theme._View.View (E:\hexo\blog\node_modules\hexo\lib\theme\index.js:37:10)
    at Theme.setView (E:\hexo\blog\node_modules\hexo\lib\theme\index.js:71:20)
    at E:\hexo\blog\node_modules\hexo\lib\theme\processors\view.js:14:14
    at tryCatcher (E:\hexo\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\hexo\blog\node_modules\bluebird\js\release\promise.js:503:31)
    at Promise._settlePromise (E:\hexo\blog\node_modules\bluebird\js\release\promise.js:560:18)
    at Promise._settlePromise0 (E:\hexo\blog\node_modules\bluebird\js\release\promise.js:605:10)
    at Promise._settlePromises (E:\hexo\blog\node_modules\bluebird\js\release\promise.js:684:18)
    at Promise._fulfill (E:\hexo\blog\node_modules\bluebird\js\release\promise.js:629:18)
    at Promise._resolveCallback (E:\hexo\blog\node_modules\bluebird\js\release\promise.js:424:57)
    at Promise._settlePromiseFromHandler (E:\hexo\blog\node_modules\bluebird\js\release\promise.js:515:17)
    at Promise._settlePromise (E:\hexo\blog\node_modules\bluebird\js\release\promise.js:560:18)
    at Promise._settlePromise0 (E:\hexo\blog\node_modules\bluebird\js\release\promise.js:605:10)
    at Promise._settlePromises (E:\hexo\blog\node_modules\bluebird\js\release\promise.js:684:18)
    at Promise._fulfill (E:\hexo\blog\node_modules\bluebird\js\release\promise.js:629:18)
    at E:\hexo\blog\node_modules\bluebird\js\release\nodeback.js:42:21
    at E:\hexo\blog\node_modules\graceful-fs\graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)

**Comment by Molunerfinn** [comment]
3.0以上即可。你应该是没有好好阅读文档。请看看你缺了安装啥。
并且你没有按照issue模板提交issue，本issue关闭。

**Comment by monkeyip** [comment]
> 主题对hexo的版本有要求吗？我使用的hexo3.2.0，配置完了提示错误：错误描述如下
> 
> ERROR Process failed: layout/includes/slide/script.pug
> TypeError: Cannot read property 'compile' of undefined
> at Theme._View.View.View._precompile (E:\hexo\blog\node_modules\hexo\lib\theme\view.js:104:23)
> at Theme._View.View.View (E:\hexo\blog\node_modules\hexo\lib\theme\view.js:13:8)
> at new Theme._View.View (E:\hexo\blog\node_modules\hexo\lib\theme\index.js:37:10)
> at Theme.setView (E:\hexo\blog\node_modules\hexo\lib\theme\index.js:71:20)
> at E:\hexo\blog\node_modules\hexo\lib\theme\processors\view.js:14:14
> at tryCatcher (E:\hexo\blog\node_modules\bluebird\js\release\util.js:16:23)
> at Promise._settlePromiseFromHandler (E:\hexo\blog\node_modules\bluebird\js\release\promise.js:503:31)
> at Promise._settlePromise (E:\hexo\blog\node_modules\bluebird\js\release\promise.js:560:18)
> at Promise._settlePromise0 (E:\hexo\blog\node_modules\bluebird\js\release\promise.js:605:10)
> at Promise._settlePromises (E:\hexo\blog\node_modules\bluebird\js\release\promise.js:684:18)
> at Promise._fulfill (E:\hexo\blog\node_modules\bluebird\js\release\promise.js:629:18)
> at Promise._resolveCallback (E:\hexo\blog\node_modules\bluebird\js\release\promise.js:424:57)
> at Promise._settlePromiseFromHandler (E:\hexo\blog\node_modules\bluebird\js\release\promise.js:515:17)
> at Promise._settlePromise (E:\hexo\blog\node_modules\bluebird\js\release\promise.js:560:18)
> at Promise._settlePromise0 (E:\hexo\blog\node_modules\bluebird\js\release\promise.js:605:10)
> at Promise._settlePromises (E:\hexo\blog\node_modules\bluebird\js\release\promise.js:684:18)
> at Promise._fulfill (E:\hexo\blog\node_modules\bluebird\js\release\promise.js:629:18)
> at E:\hexo\blog\node_modules\bluebird\js\release\nodeback.js:42:21
> at E:\hexo\blog\node_modules\graceful-fs\graceful-fs.js:78:16
> at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)

你的问题解决了吗，我今天安装也遇到这个问题了。

**Comment by Molunerfinn** [comment]
@monkeyip 你的package.json里内容是啥样的？以及你的hexo博客的目录结构是什么？光光一句报错，你要让人怎么帮你？至少多给点信息啊

**Comment by Molunerfinn** [comment]
你一句提问，就要让开发者花很多时间去复现，成本很高的。如果想要得到彻底的帮助，至少提供充分的信息或者提供一个可以复现的仓库，我能跑一下也好啊
